// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Worktime.Infrastructure.Persistence;

#nullable disable

namespace Worktime.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorktimeDbContext))]
    [Migration("20261005172022_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Worktime.Domain.Assignments.AssignmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid?>("PreferredSupervisorId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_supervisor_id");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedById")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_requests");

                    b.HasIndex("PreferredSupervisorId")
                        .HasDatabaseName("ix_assignment_requests_preferred_supervisor_id");

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_requests_pending")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("assignment_requests", (string)null);
                });

            modelBuilder.Entity("Worktime.Domain.Permissions.RolePermission", b =>
                {
                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Permission")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission");

                    b.HasKey("Role", "Permission")
                        .HasName("pk_role_permissions");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Worktime.Domain.Punch.PunchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_punch_sessions");

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasDatabaseName("ix_punch_sessions_open")
                        .HasFilter("ended_at IS NULL");

                    b.ToTable("punch_sessions", (string)null);
                });

            modelBuilder.Entity("Worktime.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid")
                        .HasColumnName("supervisor_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("SupervisorId")
                        .HasDatabaseName("ix_users_supervisor_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Worktime.Domain.WorkLogs.WorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_work_logs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_work_logs_status");

                    b.HasIndex("WorkerId", "StartAt")
                        .HasDatabaseName("ix_work_logs_worker_id_start_at");

                    b.ToTable("work_logs", (string)null);
                });

            modelBuilder.Entity("Worktime.Domain.WorkLogs.WorkLogEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("From")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to");

                    b.Property<Guid>("WorkLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_log_id");

                    b.HasKey("Id")
                        .HasName("pk_work_log_events");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_work_log_events_actor_id");

                    b.HasIndex("WorkLogId")
                        .HasDatabaseName("ix_work_log_events_work_log_id");

                    b.ToTable("work_log_events", (string)null);
                });

            modelBuilder.Entity("Worktime.Domain.Assignments.AssignmentRequest", b =>
                {
                    b.HasOne("Worktime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("PreferredSupervisorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assignment_requests_users_preferred_supervisor_id");

                    b.HasOne("Worktime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_requests_users_worker_id");
                });

            modelBuilder.Entity("Worktime.Domain.Punch.PunchSession", b =>
                {
                    b.HasOne("Worktime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_punch_sessions_users_worker_id");
                });

            modelBuilder.Entity("Worktime.Domain.Users.User", b =>
                {
                    b.HasOne("Worktime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_supervisor_id");
                });

            modelBuilder.Entity("Worktime.Domain.WorkLogs.WorkLog", b =>
                {
                    b.HasOne("Worktime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_logs_users_worker_id");
                });

            modelBuilder.Entity("Worktime.Domain.WorkLogs.WorkLogEvent", b =>
                {
                    b.HasOne("Worktime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_log_events_users_actor_id");

                    b.HasOne("Worktime.Domain.WorkLogs.WorkLog", null)
                        .WithMany("History")
                        .HasForeignKey("WorkLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_log_events_work_logs_work_log_id");
                });

            modelBuilder.Entity("Worktime.Domain.WorkLogs.WorkLog", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
